### ISSUE TITLE
IFTTT integration?

### ISSUE THREAD

**Issue by brian-villanueva** [jparkerweb/wdw-adr-checker#1]
I like your bookmarklet idea! One thing that might be useful would be to have the option of triggering IFTTT when a reservation is found, so that you can start the bookmarklet and walk away from your computer. IFTTT could trigger an SMS text, phone call, or email notification to let you know if anything was found.

I saw this simple example, so I believe it's possible:
https://gist.github.com/thegabrielstein/02b1fb5c8c6285e41f1826d3d06ed7c8

**Comment by joeyman178** [comment]
Usually too late to reserve by then.

**Comment by justin-parker** [comment]
Yeah, good idea, but from my experience I have to agree with @joeyman178. I would run the script in a side window anytime I was sitting in front of my computer.  I was able to score Space 220 and Olga's withing a few days!  Really helped me for my trip in Dec 2021, so just sharing if it could help others.  Please feel free to open issues if it is no longer compatible with the existing reservation site, as I have not tried it in some time.

**Comment by joeyman178** [comment]
> Yeah, good idea, but from my experience I have to agree with @joeyman178. I would run the script in a side window anytime I was sitting in front of my computer.  I was able to score Space 220 and Olga's withing a few days!  Really helped me for my trip in Dec 2021, so just sharing if it could help others.  Please feel free to open issues if it is no longer compatible with the existing reservation site, as I have not tried it in some time.

Thanks Justin. I will be heading to Disney in late July, so will definitely look into using this for around that time. Any tips or recommendations for the process? Parks booked first or restaurants?

Thank you for your help!

**Comment by jparkerweb** [comment]
Closing this due to it probably being too late to get a reservation once IFTTT triggers.

@joeyman178 if you still want to chat about your trip, send me an email and we can connect:
`jparkerweb+wdw-adr-checker@gmail.com`
