### ISSUE TITLE
Session Timeouts

### ISSUE THREAD

**Issue by pdgoldsmith** [jparkerweb/wdw-adr-checker#2]
Great bookmarklet!  I noticed that somewhere around 300 to 350 searches the Disney website will expire our session the the tool stops working until you manually log in again and start the tool again.  I'm not sure how to fix this.  Maybe a periodic auto-refresh of the site?

**Comment by brian-villanueva** [comment]
I've noticed the same thing, but I think Disney is expiring the session after a certain amount of time, even if you stay active. So you need to login again after some period of time.

**Comment by Jchri010** [comment]
Anyway to expand this to other Disney reservations such as Bibbidi Bobbidi Boutique?

**Comment by jparkerweb** [comment]
@Jchri010 I added a beta version to check Bibbidi Bobbidi Boutique
(check here: https://github.com/jparkerweb/wdw-adr-checker#bibbidi-bobbidi-boutique-beta)

Closing this `Session Timeouts` issue as the checker will still work but you may to to sign back in to add the reservation under your account (I'm welcome to PR's if anyone has ideas).
