### ISSUE TITLE
Enchanting Extra Reservations 

### ISSUE THREAD

**Issue by Jchri010** [jparkerweb/wdw-adr-checker#3]
Anyway to expand this to other Disney reservations such as Bibbidi Bobbidi Boutique?

**Comment by jparkerweb** [comment]
added BETA version here:
https://github.com/jparkerweb/wdw-adr-checker#bibbidi-bobbidi-boutique-beta

**Comment by jparkerweb** [comment]
@Jchri010 let me know if this works!

**Comment by Jchri010** [comment]
@jparkerweb 
It appears to be working, thank you for the addition. For this and the ADR checker, do you know how long each session is active for before you need to refresh and log back in?

I'm curious of the code developed on dining alert site such as stakeout/mouse watcher/etc. As an example I had the ADR up and running for a restaurant and did not get a "beep" or any availability but I did get a stakeout alert. I am wondering if the session expires, even though it appears to still be checking. 

Do you know if there is any negative impact to having multiple tabs open in using your ADR tool? It seems to work, but the counts of searches go up very slowly. 

Thanks!
